server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8081

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create # DB 작업 시에 none이 아니면 서버가 재실행될 때 날라감
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100 # in query
    open-in-view: false
  output:
    ansi:
      enabled: always # vscode console color
logging:
  level:
    '[com.example.blog2]': DEBUG
    '[org.hibernate.type]': TRACE